### PR TITLE
Add ability to specify a custom crates.io URL

### PR DESCRIPTION
**Pull request by exFalso**
We set up a crates.io internally, and we needed a way to tell naersk to use it instead of upstream crates.io (upstream seems to be flaky sometimes when downloading a large volume of crates). This is why we added this flag, thought it may be useful for someone else too.

### CODE REVIEW

**Review by nmattia — COMMENTED** [review]
This looks good to me! @Patryk27 ?

**Review by Patryk27 — APPROVED** [review]
Looks awesome, thanks 🙂

**Comment by Patryk27** [comment]
Ah, there seem to be some conflicts - would you mind rebasing, @exFalso? :eyes:

**Comment by Patryk27** [comment]
Hi, @exFalso - are you still interested in this MR? 🙂 

If not, I can close it and rebase it myself later, just lemme know.

**Comment by exFalso** [comment]
Hmm I'm not seeing any conflicts, merging `nix-community:naersk` returns up-to-date, are there some kind of special rules on the repo?

**Comment by nmattia** [comment]
I think it's just complaining the README is not up-to-date! It needs the new option added to it:

```
203c203
< | `cratesDownloadUrl` | Url for downloading crates from an alternative source |
---
> | `cratesDownloadUrl` | Url for downloading crates from an alternative source Default: `"https://crates.io/"` |
error: builder for '/nix/store/2b3xsb9y6c2bqcjbh73jxf3kn7s85qh9-readme-test.drv' failed with exit code 1;
       last 4 log lines:
       > 203c203
       > < | `cratesDownloadUrl` | Url for downloading crates from an alternative source |
       > ---
       > > | `cratesDownloadUrl` | Url for downloading crates from an alternative source Default: `"https://crates.io/"` |
       For full logs, run 'nix log /nix/store/2b3xsb9y6c2bqcjbh73jxf3kn7s85qh9-readme-test.drv'.
```

You can either try to do it by hand, or simply run [script/gen](https://github.com/nix-community/naersk/blob/88cd22380154a2c36799fe8098888f0f59861a15/script/gen)

**Review by Patryk27 — APPROVED** [review]

**Comment by Patryk27** [comment]
Ah, I see - Naersk's repository is configured to rebase-and-merges only and so you'd have to rebase and _squash_ all commits together to avoid conflicts :eyes:

(that is, even with the current commit GitHub still says `This branch cannot be rebased due to conflicts` since it cannot perform this rebase on its own)

**Comment by Patryk27** [comment]
Hi, @exFalso - could you squash all of the commits here, then? 🙂 

I'd do it myself even, but I don't have such permissions in this repository, hence this re-ping :innocent:

**Review by Patryk27 — APPROVED** [review]

**Pull request merged**
