### PR TITLE
Fix support for `.cargo/config`

### PR DESCRIPTION
**Pull request by Patryk27**
Before https://github.com/nix-community/naersk/pull/300, our `builtinz.toTOML` used to return a string representing the serialized document which was later redirected into a file:

https://github.com/nix-community/naersk/pull/300/files#diff-b6b537316f2d29c8faf178a110366796811d1bc72f694262c7d2efad79aa984bL238

Over that merge request, this was changed to return a path, to make it consistent with how nixpkgs' formatters work - but I haven't noticed one place that still _read_ the file instead of returning a path (which was fine before, since the code did `echo ... > ...`, but is not a correct thing to do for `cp`).

Closes https://github.com/nix-community/naersk/issues/305.

### CODE REVIEW

**Review by nmattia — DISMISSED** [review]
Thanks for the fix, and the test!

**Comment by Patryk27** [comment]
Small fix: tests for nixpkgs-21.05 used too old Cargo, from before support for custom environmental variables was introduced, so I've had to adjust the new test a bit.

**Comment by Patryk27** [comment]
(cc @nmattia, since GitHub requires another ✅ here :smile:)

**Review by nmattia — APPROVED** [review]
There you go :)

**Pull request merged**
