### PR TITLE
Fix non-deterministic dependency builds

### PR DESCRIPTION
**Pull request by sandro-fugro**
### Problem

Hi there,

I wasn't able to reproduce a hello world crate when built multiple times:

```
❯ nix build . -L --enforce-determinism --repeat 2 --keep-failed
warning: Git tree '/home/opeik/dev/hello-world' is dirty
hello-world-deps> unpacking sources
hello-world-deps> unpacking source archive /nix/store/kcijkqzh45qv5hr6jjg7s5qn3jbhdj7f-dummy-src
hello-world-deps> source root is dummy-src
hello-world-deps> patching sources
hello-world-deps> configuring
hello-world-deps> [naersk] cargo_version (read): 1.56.0 (4ed5d137b 2021-10-04)
hello-world-deps> [naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
hello-world-deps> [naersk] cargo_release: --release
hello-world-deps> [naersk] cargo_options: --locked
hello-world-deps> [naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
hello-world-deps> [naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
hello-world-deps> [naersk] RUST_TEST_THREADS: 16
hello-world-deps> [naersk] cargo_bins_jq_filter: .
hello-world-deps> [naersk] cargo_build_output_json (created): /build/tmp.CEGDgnF18s
hello-world-deps> [naersk] crate_sources: /nix/store/7c9z5md5f8mjizn7p0ynxac9rbgnfhq1-crates-io
hello-world-deps> [naersk] RUSTFLAGS:
hello-world-deps> [naersk] CARGO_BUILD_RUSTFLAGS: -D warnings
hello-world-deps> [naersk] CARGO_BUILD_RUSTFLAGS (updated): -D warnings --remap-path-prefix /nix/store/7c9z5md5f8mjizn7p0ynxac9rbgnfhq1-crates-io=/sources
hello-world-deps> building
hello-world-deps> cargo --locked build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
hello-world-deps>    Compiling hello-world v0.1.0 (/build/dummy-src)
hello-world-deps>     Finished release [optimized] target(s) in 0.23s
hello-world-deps> running tests
hello-world-deps> cargo --locked test $cargo_release -j "$NIX_BUILD_CORES"
hello-world-deps>    Compiling hello-world v0.1.0 (/build/dummy-src)
hello-world-deps>     Finished release [optimized] target(s) in 0.17s
hello-world-deps>      Running unittests (out/release/deps/hello_world-6a68186dc9630b7a)
hello-world-deps> running 0 tests
hello-world-deps> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
hello-world-deps>    Doc-tests hello-world
hello-world-deps> running 0 tests
hello-world-deps> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
hello-world-deps> installing
hello-world-deps> /*stdin*\            :  0.90%   ( 10240 =>     92 bytes, /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0/target.tar.zst)
hello-world-deps> post-installation fixup
hello-world-deps> shrinking RPATHs of ELF executables and libraries in /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0
hello-world-deps> strip is /nix/store/5ddb4j8z84p6sjphr0kh6cbq5jd12ncs-binutils-2.35.1/bin/strip
hello-world-deps> patching script interpreter paths in /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0
hello-world-deps> checking for references to /build/ in /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0...
hello-world-deps> unpacking sources
hello-world-deps> unpacking source archive /nix/store/kcijkqzh45qv5hr6jjg7s5qn3jbhdj7f-dummy-src
hello-world-deps> source root is dummy-src
hello-world-deps> patching sources
hello-world-deps> configuring
hello-world-deps> [naersk] cargo_version (read): 1.56.0 (4ed5d137b 2021-10-04)
hello-world-deps> [naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
hello-world-deps> [naersk] cargo_release: --release
hello-world-deps> [naersk] cargo_options: --locked
hello-world-deps> [naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
hello-world-deps> [naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
hello-world-deps> [naersk] RUST_TEST_THREADS: 16
hello-world-deps> [naersk] cargo_bins_jq_filter: .
hello-world-deps> [naersk] cargo_build_output_json (created): /build/tmp.BfI9dQSjcl
hello-world-deps> [naersk] crate_sources: /nix/store/7c9z5md5f8mjizn7p0ynxac9rbgnfhq1-crates-io
hello-world-deps> [naersk] RUSTFLAGS:
hello-world-deps> [naersk] CARGO_BUILD_RUSTFLAGS: -D warnings
hello-world-deps> [naersk] CARGO_BUILD_RUSTFLAGS (updated): -D warnings --remap-path-prefix /nix/store/7c9z5md5f8mjizn7p0ynxac9rbgnfhq1-crates-io=/sources
hello-world-deps> building
hello-world-deps> cargo --locked build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
hello-world-deps>    Compiling hello-world v0.1.0 (/build/dummy-src)
hello-world-deps>     Finished release [optimized] target(s) in 0.25s
hello-world-deps> running tests
hello-world-deps> cargo --locked test $cargo_release -j "$NIX_BUILD_CORES"
hello-world-deps>    Compiling hello-world v0.1.0 (/build/dummy-src)
hello-world-deps>     Finished release [optimized] target(s) in 0.19s
hello-world-deps>      Running unittests (out/release/deps/hello_world-6a68186dc9630b7a)
hello-world-deps> running 0 tests
hello-world-deps> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
hello-world-deps>    Doc-tests hello-world
hello-world-deps> running 0 tests
hello-world-deps> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
hello-world-deps> installing
hello-world-deps> /*stdin*\            :  0.90%   ( 10240 =>     92 bytes, /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0/target.tar.zst)
hello-world-deps> post-installation fixup
hello-world-deps> shrinking RPATHs of ELF executables and libraries in /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0
hello-world-deps> strip is /nix/store/5ddb4j8z84p6sjphr0kh6cbq5jd12ncs-binutils-2.35.1/bin/strip
hello-world-deps> patching script interpreter paths in /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0
hello-world-deps> checking for references to /build/ in /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0...
error: output '/nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0' of '/nix/store/j71p65hknwfycib9xlj4bjkrfn3gbqnk-hello-world-deps-0.1.0.drv' differs from '/nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0.check' from previous round
note: keeping build directory '/tmp/nix-build-hello-world-deps-0.1.0.drv-9'
```

```
❯ diffoscope /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0/target.tar.zst \
/nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0.check/target.tar.zst
--- /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0/target.tar.zst
+++ /nix/store/dlzm191v7hcy65ks6ii4sfl04nd42k7m-hello-world-deps-0.1.0.check/target.tar.zst
├── target.tar
│ ├── file list
│ │ @@ -1 +1 @@
│ │ -drwxr-xr-x   0 nixbld    (1000) nixbld     (100)        0 2021-11-03 07:21:08.000000 target/
│ │ +drwxr-xr-x   0 nixbld    (1000) nixbld     (100)        0 2021-11-03 07:21:07.000000 target/
```

### Solution

It seems that the builds were failing due to the dependency tarball having different modification dates. I've referenced [`fetchCargoTarball`](https://github.com/NixOS/nixpkgs/blob/a0dbe47318bbab7559ffbfa7c4872a517833409f/pkgs/build-support/rust/fetchCargoTarball.nix#L75) and implemented similar measures.

### Testing

To test the fix, I made a crate containing the [`tokio` TCP echo server example](https://github.com/tokio-rs/tokio#example) and ran the build with forced determinism for 30 repetitions. 

```
❯ nix build . -L --enforce-determinism --repeat 30 --keep-failed
```

It now builds reproducibility!

### CODE REVIEW

**Comment by sandro-fugro** [comment]
Sorry about the force-pushes. I realized I had accidentally ran nixfmt which made for a very big diff.

**Review by nmattia — APPROVED** [review]
Oh neat, didn't know of https://reproducible-builds.org/docs/archives/! That's great. Thanks!

**Comment by nmattia** [comment]
Let me know if you're happy with this and we can merge!

CC @jonringer

**Comment by sandro-fugro** [comment]
Glad to help! You may want to use [`enforce-determinism`](https://nixos.org/manual/nix/unstable/advanced-topics/diff-hook.html?highlight=deter#automatic-and-optionally-enforced-determinism-verification) in ci to catch non-deterministic builds in the future.

**Comment by nmattia** [comment]
That would be nice, but I'm guessing it will slow down the tests a fair bit. Alright, merging now!

**Pull request merged**
